"use strict";
var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
};
var __metadata = (this && this.__metadata) || function (k, v) {
    if (typeof Reflect === "object" && typeof Reflect.metadata === "function") return Reflect.metadata(k, v);
};
var _a;
Object.defineProperty(exports, "__esModule", { value: true });
exports.Migration = exports.PrimaryIdAutoGenerated = void 0;
const typeorm_1 = require("typeorm");
const _1 = require(".");
exports.PrimaryIdAutoGenerated = ((_a = process.env.DATABASE) === null || _a === void 0 ? void 0 : _a.startsWith("mongodb"))
    ? typeorm_1.ObjectIdColumn
    : typeorm_1.PrimaryGeneratedColumn;
let Migration = class Migration extends _1.BaseClassWithoutId {
};
__decorate([
    (0, exports.PrimaryIdAutoGenerated)(),
    __metadata("design:type", Number)
], Migration.prototype, "id", void 0);
__decorate([
    (0, typeorm_1.Column)({ type: "bigint" }),
    __metadata("design:type", Number)
], Migration.prototype, "timestamp", void 0);
__decorate([
    (0, typeorm_1.Column)(),
    __metadata("design:type", String)
], Migration.prototype, "name", void 0);
Migration = __decorate([
    (0, typeorm_1.Entity)("migrations")
], Migration);
exports.Migration = Migration;
